config/routes.rb
Rails.application.routes.draw do
  resources :venues
  get 'metro_search/show'

  get 'metro_search/search'

end

app/models/venue.rb
class Venue < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/metro_search_controller.rb
require 'songkickr'

class MetroSearchController < ApplicationController

  attr_reader :sk, :per_page

  def initialize
    @@sk = Songkickr::Remote.new config.songkick_api[:api_key]
    @per_page =  100
  end


  def index
  end

  def search
    sk.location_search build_query(params)
  end




end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:sk_id, :spotify_playlist_id, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/metro_search_helper.rb
module MetroSearchHelper

  @per_page = 100

  def location_query(params = {})
      if params.fetch(:q, nil)
        { :query =>  params[:q] }
      elsif params.fetch(:geo, nil)
        { :location => "geo:#{get_lat(params[:geo])},#{get_lng(params[:geo])}" }
      else
        throw ArgumentError 'Did not get enough parameters to search by location'
      end
  end

  def build_query(params)
    location_query(params).merge(:per_page => 100)
  end

  def get_lat(coordinates)
    get_coords(coordinates)[0]
  end

  def get_lng(coordinates)
    get_coords(coordinates)[1]
  end

  def get_coords(coordinates)
    @coords ||= coordinates.split(",")
  end

end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoundsLocal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/metro_search/index.html.erb
<h1>MetroSearch#sindex</h1>
<p>Find me in app/views/metro_search/show.html.erb</p>

app/views/metro_search/result.html.erb
<h1>MetroSearch#result</h1>
<p>Find me in app/views/metro_search/result.html.erb</p>

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sk_id %><br>
    <%= f.text_field :sk_id %>
  </div>
  <div class="field">
    <%= f.label :spotify_playlist_id %><br>
    <%= f.text_field :spotify_playlist_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Venues</h1>

<table>
  <thead>
    <tr>
      <th>Sk</th>
      <th>Spotify playlist</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.sk_id %></td>
        <td><%= venue.spotify_playlist_id %></td>
        <td><%= venue.name %></td>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sk:</strong>
  <%= @venue.sk_id %>
</p>

<p>
  <strong>Spotify playlist:</strong>
  <%= @venue.spotify_playlist_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @venue.name %>
</p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>